// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV1fNVEbcmq3KNCHfTTVhUxRsvq6qoeAo',
    appId: '1:276564211292:web:64c857637648aa7cb95899',
    messagingSenderId: '276564211292',
    projectId: 'flutter-chat-app-1aa6e',
    authDomain: 'flutter-chat-app-1aa6e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1aa6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYgysqlI1Y1InXutxCwVyPvv19k9gxDU0',
    appId: '1:276564211292:android:38a07ac9dde43a8bb95899',
    messagingSenderId: '276564211292',
    projectId: 'flutter-chat-app-1aa6e',
    storageBucket: 'flutter-chat-app-1aa6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ3UXTSN54N4DArE1YsIL_WdwljuaZbBo',
    appId: '1:276564211292:ios:5e494931ed42ea59b95899',
    messagingSenderId: '276564211292',
    projectId: 'flutter-chat-app-1aa6e',
    storageBucket: 'flutter-chat-app-1aa6e.firebasestorage.app',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ3UXTSN54N4DArE1YsIL_WdwljuaZbBo',
    appId: '1:276564211292:ios:5e494931ed42ea59b95899',
    messagingSenderId: '276564211292',
    projectId: 'flutter-chat-app-1aa6e',
    storageBucket: 'flutter-chat-app-1aa6e.firebasestorage.app',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV1fNVEbcmq3KNCHfTTVhUxRsvq6qoeAo',
    appId: '1:276564211292:web:9a5462c3932e8ed5b95899',
    messagingSenderId: '276564211292',
    projectId: 'flutter-chat-app-1aa6e',
    authDomain: 'flutter-chat-app-1aa6e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1aa6e.firebasestorage.app',
  );
}